# Generated by Django 5.1.1 on 2024-09-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacher_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('t', 'Teacher'), ('s', 'Super Teacher')], default='t', max_length=100),
        ),
    ]
